# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Repositories\Geekbrains_Client_Server_App\hw_plots\main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.task_1 = QtWidgets.QWidget()
        self.task_1.setObjectName("task_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.task_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.task1PlotLayout = QtWidgets.QGridLayout()
        self.task1PlotLayout.setObjectName("task1PlotLayout")
        self.gridLayout_2.addLayout(self.task1PlotLayout, 2, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.task_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.task1MaxRangeXDsb = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.task1MaxRangeXDsb.setMinimum(-1000.0)
        self.task1MaxRangeXDsb.setMaximum(1000.0)
        self.task1MaxRangeXDsb.setProperty("value", 10.0)
        self.task1MaxRangeXDsb.setObjectName("task1MaxRangeXDsb")
        self.gridLayout_3.addWidget(self.task1MaxRangeXDsb, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.task1MinRangeXDsb = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task1MinRangeXDsb.sizePolicy().hasHeightForWidth())
        self.task1MinRangeXDsb.setSizePolicy(sizePolicy)
        self.task1MinRangeXDsb.setMinimum(-1000.0)
        self.task1MinRangeXDsb.setMaximum(1000.0)
        self.task1MinRangeXDsb.setObjectName("task1MinRangeXDsb")
        self.gridLayout_3.addWidget(self.task1MinRangeXDsb, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 1)
        self.task1StepRangeXDsb = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.task1StepRangeXDsb.setMinimum(0.1)
        self.task1StepRangeXDsb.setObjectName("task1StepRangeXDsb")
        self.gridLayout_3.addWidget(self.task1StepRangeXDsb, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.task1ApplyBtn = QtWidgets.QPushButton(self.task_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task1ApplyBtn.sizePolicy().hasHeightForWidth())
        self.task1ApplyBtn.setSizePolicy(sizePolicy)
        self.task1ApplyBtn.setObjectName("task1ApplyBtn")
        self.verticalLayout.addWidget(self.task1ApplyBtn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.verticalLayout, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.task_1)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.tabWidget.addTab(self.task_1, "")
        self.task_2 = QtWidgets.QWidget()
        self.task_2.setObjectName("task_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.task_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.task_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 1)
        self.task2MaxRangeXDsb = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task2MaxRangeXDsb.sizePolicy().hasHeightForWidth())
        self.task2MaxRangeXDsb.setSizePolicy(sizePolicy)
        self.task2MaxRangeXDsb.setProperty("value", 10.0)
        self.task2MaxRangeXDsb.setObjectName("task2MaxRangeXDsb")
        self.gridLayout_4.addWidget(self.task2MaxRangeXDsb, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.task2MinRangeXDsb = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task2MinRangeXDsb.sizePolicy().hasHeightForWidth())
        self.task2MinRangeXDsb.setSizePolicy(sizePolicy)
        self.task2MinRangeXDsb.setObjectName("task2MinRangeXDsb")
        self.gridLayout_4.addWidget(self.task2MinRangeXDsb, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 2, 0, 1, 1)
        self.task2StepRangeXDsb = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task2StepRangeXDsb.sizePolicy().hasHeightForWidth())
        self.task2StepRangeXDsb.setSizePolicy(sizePolicy)
        self.task2StepRangeXDsb.setMinimum(0.1)
        self.task2StepRangeXDsb.setObjectName("task2StepRangeXDsb")
        self.gridLayout_4.addWidget(self.task2StepRangeXDsb, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.task2ApplyBtn = QtWidgets.QPushButton(self.task_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task2ApplyBtn.sizePolicy().hasHeightForWidth())
        self.task2ApplyBtn.setSizePolicy(sizePolicy)
        self.task2ApplyBtn.setObjectName("task2ApplyBtn")
        self.verticalLayout_2.addWidget(self.task2ApplyBtn)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 0, 0, 1, 1)
        self.task2PlotLayout = QtWidgets.QGridLayout()
        self.task2PlotLayout.setObjectName("task2PlotLayout")
        self.gridLayout_5.addLayout(self.task2PlotLayout, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.task_2)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 1, 0, 1, 1)
        self.tabWidget.addTab(self.task_2, "")
        self.task_3 = QtWidgets.QWidget()
        self.task_3.setObjectName("task_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.task_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_7 = QtWidgets.QLabel(self.task_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 0, 0, 1, 1)
        self.task3MathFuncLne = QtWidgets.QLineEdit(self.task_3)
        self.task3MathFuncLne.setObjectName("task3MathFuncLne")
        self.gridLayout_8.addWidget(self.task3MathFuncLne, 0, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.task_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.task3MaxRangeXDsb = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.task3MaxRangeXDsb.setMinimum(-1000.0)
        self.task3MaxRangeXDsb.setMaximum(1000.0)
        self.task3MaxRangeXDsb.setProperty("value", 10.0)
        self.task3MaxRangeXDsb.setObjectName("task3MaxRangeXDsb")
        self.gridLayout_7.addWidget(self.task3MaxRangeXDsb, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 0, 0, 1, 1)
        self.task3MinRangeXDsb = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task3MinRangeXDsb.sizePolicy().hasHeightForWidth())
        self.task3MinRangeXDsb.setSizePolicy(sizePolicy)
        self.task3MinRangeXDsb.setMinimum(-1000.0)
        self.task3MinRangeXDsb.setMaximum(1000.0)
        self.task3MinRangeXDsb.setObjectName("task3MinRangeXDsb")
        self.gridLayout_7.addWidget(self.task3MinRangeXDsb, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 2, 0, 1, 1)
        self.task3StepRangeXDsb = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.task3StepRangeXDsb.setMinimum(0.1)
        self.task3StepRangeXDsb.setObjectName("task3StepRangeXDsb")
        self.gridLayout_7.addWidget(self.task3StepRangeXDsb, 2, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.task3ApplyBtn = QtWidgets.QPushButton(self.task_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task3ApplyBtn.sizePolicy().hasHeightForWidth())
        self.task3ApplyBtn.setSizePolicy(sizePolicy)
        self.task3ApplyBtn.setObjectName("task3ApplyBtn")
        self.verticalLayout_3.addWidget(self.task3ApplyBtn)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.gridLayout_8.addLayout(self.verticalLayout_3, 0, 2, 2, 1)
        self.task3PlotLayout = QtWidgets.QGridLayout()
        self.task3PlotLayout.setObjectName("task3PlotLayout")
        self.gridLayout_8.addLayout(self.task3PlotLayout, 1, 0, 1, 2)
        self.tabWidget.addTab(self.task_3, "")
        self.task_4 = QtWidgets.QWidget()
        self.task_4.setObjectName("task_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.task_4)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.task4PlotLayout = QtWidgets.QGridLayout()
        self.task4PlotLayout.setObjectName("task4PlotLayout")
        self.gridLayout_9.addLayout(self.task4PlotLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.task_4, "")
        self.task_5 = QtWidgets.QWidget()
        self.task_5.setObjectName("task_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.task_5)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_11 = QtWidgets.QLabel(self.task_5)
        self.label_11.setObjectName("label_11")
        self.gridLayout_10.addWidget(self.label_11, 0, 0, 1, 1)
        self.task5UsernameLne = QtWidgets.QLineEdit(self.task_5)
        self.task5UsernameLne.setObjectName("task5UsernameLne")
        self.gridLayout_10.addWidget(self.task5UsernameLne, 0, 1, 1, 1)
        self.task5ApplyBtn = QtWidgets.QPushButton(self.task_5)
        self.task5ApplyBtn.setObjectName("task5ApplyBtn")
        self.gridLayout_10.addWidget(self.task5ApplyBtn, 0, 2, 1, 1)
        self.task5PlotLayout = QtWidgets.QGridLayout()
        self.task5PlotLayout.setObjectName("task5PlotLayout")
        self.gridLayout_10.addLayout(self.task5PlotLayout, 1, 0, 1, 3)
        self.tabWidget.addTab(self.task_5, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Range X"))
        self.label.setText(_translate("MainWindow", "Min"))
        self.label_2.setText(_translate("MainWindow", "Max"))
        self.label_5.setText(_translate("MainWindow", "Step"))
        self.task1ApplyBtn.setText(_translate("MainWindow", "Apply"))
        self.label_12.setText(_translate("MainWindow", "y=x*2- cos(x)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.task_1), _translate("MainWindow", "Task 1"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Range X"))
        self.label_4.setText(_translate("MainWindow", "Max"))
        self.label_3.setText(_translate("MainWindow", "Min"))
        self.label_6.setText(_translate("MainWindow", "Step"))
        self.task2ApplyBtn.setText(_translate("MainWindow", "Apply"))
        self.label_13.setText(_translate("MainWindow", "y=x^3- sqrt(x)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.task_2), _translate("MainWindow", "Task 2"))
        self.label_7.setText(_translate("MainWindow", "Math function"))
        self.task3MathFuncLne.setText(_translate("MainWindow", "y=x**2"))
        self.task3MathFuncLne.setPlaceholderText(_translate("MainWindow", "y=x**2"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Range X"))
        self.label_8.setText(_translate("MainWindow", "Min"))
        self.label_9.setText(_translate("MainWindow", "Max"))
        self.label_10.setText(_translate("MainWindow", "Step"))
        self.task3ApplyBtn.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.task_3), _translate("MainWindow", "Task 3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.task_4), _translate("MainWindow", "Task 4"))
        self.label_11.setText(_translate("MainWindow", "User name"))
        self.task5ApplyBtn.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.task_5), _translate("MainWindow", "Task 5"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
