# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Repositories\Geekbrains_Client_Server_App\server\ui\server_config.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(409, 250)
        Dialog.setMinimumSize(QtCore.QSize(400, 200))
        Dialog.setMaximumSize(QtCore.QSize(409, 250))
        font = QtGui.QFont()
        font.setPointSize(8)
        Dialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.btns_h_layout = QtWidgets.QHBoxLayout()
        self.btns_h_layout.setObjectName("btns_h_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.btns_h_layout.addItem(spacerItem)
        self.save_btn = QtWidgets.QPushButton(Dialog)
        self.save_btn.setObjectName("save_btn")
        self.btns_h_layout.addWidget(self.save_btn)
        self.cancel_btn = QtWidgets.QPushButton(Dialog)
        self.cancel_btn.setObjectName("cancel_btn")
        self.btns_h_layout.addWidget(self.cancel_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.btns_h_layout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.btns_h_layout, 4, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(388, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 3, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.port_txb = QtWidgets.QLineEdit(Dialog)
        self.port_txb.setObjectName("port_txb")
        self.gridLayout.addWidget(self.port_txb, 1, 1, 1, 2)
        self.bind_addr_txb = QtWidgets.QLineEdit(Dialog)
        self.bind_addr_txb.setObjectName("bind_addr_txb")
        self.gridLayout.addWidget(self.bind_addr_txb, 2, 1, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mongo_db_rbn = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mongo_db_rbn.setFont(font)
        self.mongo_db_rbn.setObjectName("mongo_db_rbn")
        self.gridLayout_2.addWidget(self.mongo_db_rbn, 0, 0, 1, 3)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.db_host_txb = QtWidgets.QLineEdit(self.groupBox)
        self.db_host_txb.setObjectName("db_host_txb")
        self.gridLayout_2.addWidget(self.db_host_txb, 1, 1, 1, 2)
        self.sqlite_db_rbn = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sqlite_db_rbn.setFont(font)
        self.sqlite_db_rbn.setChecked(True)
        self.sqlite_db_rbn.setObjectName("sqlite_db_rbn")
        self.gridLayout_2.addWidget(self.sqlite_db_rbn, 2, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.db_filepath_txb = QtWidgets.QLineEdit(self.groupBox)
        self.db_filepath_txb.setObjectName("db_filepath_txb")
        self.gridLayout_2.addWidget(self.db_filepath_txb, 3, 1, 1, 1)
        self.select_file_btn = QtWidgets.QToolButton(self.groupBox)
        self.select_file_btn.setObjectName("select_file_btn")
        self.gridLayout_2.addWidget(self.select_file_btn, 3, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 3)

        self.retranslateUi(Dialog)
        self.sqlite_db_rbn.toggled['bool'].connect(self.db_filepath_txb.setEnabled)
        self.sqlite_db_rbn.toggled['bool'].connect(self.select_file_btn.setEnabled)
        self.mongo_db_rbn.toggled['bool'].connect(self.db_host_txb.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Config"))
        self.save_btn.setText(_translate("Dialog", "Save"))
        self.cancel_btn.setText(_translate("Dialog", "Cancel"))
        self.label_2.setText(_translate("Dialog", "Port"))
        self.label_3.setText(_translate("Dialog", "Bind address"))
        self.groupBox.setTitle(_translate("Dialog", "Database"))
        self.mongo_db_rbn.setText(_translate("Dialog", "Mongo"))
        self.label_4.setText(_translate("Dialog", "Host"))
        self.db_host_txb.setPlaceholderText(_translate("Dialog", "mongodb://localhost:27017/local"))
        self.sqlite_db_rbn.setText(_translate("Dialog", "Sqlite"))
        self.label.setText(_translate("Dialog", "Database file"))
        self.select_file_btn.setText(_translate("Dialog", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
